### ISSUE TITLE
When dragging and then letting it go it always goes back to starting position

### ISSUE THREAD

**Issue by Muhand** [moifort/SlideOverCard#3]
I think the title says it all, I tried looking through the code to find out whats exactly causing it but wasn't able to. 

All I have done is the following

```
ZStack {
      Color.red
      SlideOverCard() {
            VStack{
                 Text("A")
             }
       }
}
```
 

Not sure what am I doing wrong.

**Comment by GarethSomers** [comment]
Hi @Muhand I ran into the same problem. I think you just need to pass the position from a State variable.

So add `@State var position : CardPosition = .bottom` to your View and then swap your code to look like:

```
ZStack {
      Color.red
      SlideOverCard(self.$position) {
            VStack{
                 Text("A")
             }
       }
}
```

I think the reason is by just calling SlideOverCard it's using the default constructor `public init(_ position: Binding<CardPosition> = .constant(.middle), backgroundStyle: Binding<BackgroundStyle> = .constant(.solid), content: @escaping () -> Content)`

In that default constructor the use of `.constant(.middle)` is preventing the code from modifying that value (becuase it's a constant).

**Comment by Muhand** [comment]
Hi @GarethSomers,
Thank you for your response. You are actually correct. I tested it and that worked 100%.
